#!/bin/sh

go get -t -v gopkg.in/gomail.v2
go get -t -v gopkg.in/go-playground/validator.v9
go get -t -v golang.org/x/crypto/bcrypt
go get -t -v golang.org/x/net/...
go get -t -v golang.org/x/text/...
go get -t -v github.com/SermoDigital/jose/crypto
go get -t -v github.com/SermoDigital/jose/jws
go get -t -v github.com/SermoDigital/jose/jwt
go get -t -v github.com/jarcoal/httpmock
go get -t -v github.com/stretchr/testify/assert
go get -t -v github.com/PuerkitoBio/purell
go get -t -v github.com/jinzhu/copier
go get -t -v github.com/jinzhu/gorm/...
go get -t -v github.com/labstack/echo
go get -t -v github.com/labstack/echo-contrib
go get -t -v github.com/labstack/echo/middleware
go get -t -v github.com/labstack/gommon/log
go get -t -v github.com/labstack/gommon/random
go get -t -v github.com/labstack/gommon/bytes
go get -t -v github.com/satori/go.uuid
go get -t -v github.com/gorilla/...
go get -t -v github.com/dgrijalva/jwt-go
go get -t -v github.com/google/go-querystring/...
go get -t -v github.com/docker/docker/api/...
go get -t -v github.com/docker/docker/client
go get -t -v github.com/hashicorp/raft/...
go get -t -v github.com/hashicorp/raft-boltdb/...
go get -t -v zombiezen.com/go/capnproto2/...
